[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
optimizer = true
optimizer_runs = 200
solc = '0.8.22'
evm_version = 'shanghai'
bytecode_hash = 'none'
ignored_warnings_from = ["src/periphery/contracts/treasury/RevenueSplitter.sol"]
out = 'out'
libs = ['lib']
remappings = []
fs_permissions = [
  { access = "write", path = "./reports" },
  { access = "read", path = "./out" },
  { access = "read", path = "./config" },
]
ffi = true
private_key = "${PRIVATE_KEY}"

[fuzz]
runs = 1000
max_test_rejects = 20000

[profile.linea]
evm_version = 'london'

[rpc_endpoints]
mantle = "${RPC_MANTLE}"

[etherscan]
mantle = { key = "${ETHERSCAN_API_KEY_MANTLE}", chainId = "mantle" }
# See more config options https://github.com/gakonst/foundry/tree/master/config
