name: Release

on:
  push:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.repository == 'aave-dao/aave-v3-origin'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: bgd-labs/github-workflows/.github/actions/setup-node@main

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@ff7179cf129faeb3e444f56e6290adef5901f936
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
